# Generated by Django 5.1.3 on 2024-12-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flight",
            unique_together={("route", "airplane", "departure_time")},
        ),
    ]
