# Generated by Django 5.1.3 on 2024-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_airport_crew_order_route_flight_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crewmates",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
    ]
