# Generated by Django 5.1.3 on 2024-12-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_flight_crewmates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "row", "flight")},
        ),
    ]
